"""a02_foundation

Revision ID: 2ce34638ca9a
Revises: 
Create Date: 2026-10-08 01:58:10.692320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce34638ca9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_clocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_anchor', sa.DateTime(), nullable=False),
    sa.Column('server_anchor', sa.DateTime(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_clocks'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_unit', sa.String(length=16), nullable=False),
    sa.Column('pack_size', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('pack_size > 0', name=op.f('ck_products_pack_size')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku'))
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('cutoff', sa.Time(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('calculation_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('code', name=op.f('uq_stores_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('manager','operator','admin')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=120), nullable=False),
    sa.Column('old', sa.JSON(), nullable=True),
    sa.Column('new', sa.JSON(), nullable=True),
    sa.Column('server_time', sa.DateTime(), nullable=False),
    sa.Column('business_time', sa.DateTime(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_audit_events_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_store_id'), ['store_id'], unique=False)

    op.create_table('delivery_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('baseline_at', sa.DateTime(), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(), nullable=False),
    sa.Column('arrival_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_delivery_cycles_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_cycles')),
    sa.UniqueConstraint('store_id', 'baseline_at', 'arrival_at', name=op.f('uq_delivery_cycles_store_id'))
    )
    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_policy_versions_product_id_products')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_policy_versions_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_versions')),
    sa.UniqueConstraint('store_id', 'product_id', 'version', name=op.f('uq_policy_versions_store_id'))
    )
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_versions_store_id'), ['store_id'], unique=False)

    op.create_table('user_acknowledgements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text_version', sa.String(length=32), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_acknowledgements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_acknowledgements')),
    sa.UniqueConstraint('user_id', 'text_version', name=op.f('uq_user_acknowledgements_user_id'))
    )
    op.create_table('user_stores',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_user_stores_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_stores_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'store_id', name=op.f('pk_user_stores'))
    )
    op.create_table('store_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('policy_version_id', sa.Integer(), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('lead_days >= 1 AND safety_stock >= 0 AND capacity >= 0', name=op.f('ck_store_products_policy_quantities')),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_store_products_policy_version_id_policy_versions')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_store_products_product_id_products')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_store_products_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_products')),
    sa.UniqueConstraint('store_id', 'product_id', name=op.f('uq_store_products_store_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_products')
    op.drop_table('user_stores')
    op.drop_table('user_acknowledgements')
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_versions_store_id'))

    op.drop_table('policy_versions')
    op.drop_table('delivery_cycles')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_store_id'))

    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('products')
    op.drop_table('business_clocks')
    # ### end Alembic commands ###
