"""a03_parallel_base

Revision ID: 884e7a53a8c8
Revises: 2ce34638ca9a
Create Date: 2026-10-08 02:10:16.689340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884e7a53a8c8'
down_revision = '2ce34638ca9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('physical_qty', sa.Integer(), nullable=False),
    sa.Column('unsellable_qty', sa.Integer(), nullable=False),
    sa.Column('book_physical_qty', sa.Integer(), nullable=False),
    sa.Column('book_unsellable_qty', sa.Integer(), nullable=False),
    sa.Column('reconciliation_required', sa.Boolean(), nullable=False),
    sa.Column('counted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('physical_qty >= 0 AND unsellable_qty >= 0 AND unsellable_qty <= physical_qty', name=op.f('ck_inventories_count_quantities')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventories_product_id_products')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_inventories_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventories')),
    sa.UniqueConstraint('store_id', 'product_id', name=op.f('uq_inventories_store_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventories_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventories_store_id'), ['store_id'], unique=False)

    op.create_table('inventory_counts',
    sa.Column('cutoff_at', sa.DateTime(), nullable=False),
    sa.Column('baseline_physical_qty', sa.Integer(), nullable=False),
    sa.Column('baseline_unsellable_qty', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_counts_product_id_products')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_inventory_counts_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_counts')),
    sa.UniqueConstraint('store_id', 'product_id', 'cutoff_at', name=op.f('uq_inventory_counts_store_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('inventory_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_counts_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_counts_store_id'), ['store_id'], unique=False)

    op.create_table('inventory_movements',
    sa.Column('physical_delta', sa.Integer(), nullable=False),
    sa.Column('unsellable_delta', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('resulting_version', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_inventory_movements_actor_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_movements_product_id_products')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_inventory_movements_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movements')),
    sa.UniqueConstraint('store_id', 'source_type', 'source_id', 'product_id', name=op.f('uq_inventory_movements_store_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_store_id'), ['store_id'], unique=False)

    op.create_table('inventory_reconciliations',
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_reconciliations_product_id_products')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_inventory_reconciliations_resolved_by_users')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_inventory_reconciliations_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_reconciliations')),
    sa.UniqueConstraint('store_id', 'product_id', 'source_type', 'source_id', name=op.f('uq_inventory_reconciliations_store_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('inventory_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_reconciliations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_reconciliations_store_id'), ['store_id'], unique=False)

    op.create_table('manual_forecast_overrides',
    sa.Column('daily_demand', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('daily_demand >= 0 AND daily_demand <= 1000000', name=op.f('ck_manual_forecast_overrides_demand')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_manual_forecast_overrides_actor_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_manual_forecast_overrides_product_id_products')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_manual_forecast_overrides_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_forecast_overrides'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('manual_forecast_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_forecast_overrides_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_forecast_overrides_store_id'), ['store_id'], unique=False)

    op.create_table('sales_import_batches',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('source_batch_id', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('import_mode', sa.String(length=24), nullable=False),
    sa.Column('replaces_batch_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("import_mode IN ('historical','daily_posting')", name=op.f('ck_sales_import_batches_mode')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_sales_import_batches_actor_id_users')),
    sa.ForeignKeyConstraint(['replaces_batch_id'], ['sales_import_batches.id'], name=op.f('fk_sales_import_batches_replaces_batch_id_sales_import_batches')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_sales_import_batches_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_import_batches')),
    sa.UniqueConstraint('store_id', 'source_batch_id', name=op.f('uq_sales_import_batches_store_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('inventory_count_revisions',
    sa.Column('count_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('physical_qty', sa.Integer(), nullable=False),
    sa.Column('unsellable_qty', sa.Integer(), nullable=False),
    sa.Column('physical_delta', sa.Integer(), nullable=False),
    sa.Column('unsellable_delta', sa.Integer(), nullable=False),
    sa.Column('expected_version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('physical_qty >= 0 AND unsellable_qty >= 0 AND unsellable_qty <= physical_qty', name=op.f('ck_inventory_count_revisions_quantities')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_inventory_count_revisions_actor_id_users')),
    sa.ForeignKeyConstraint(['count_id'], ['inventory_counts.id'], name=op.f('fk_inventory_count_revisions_count_id_inventory_counts')),
    sa.ForeignKeyConstraint(['movement_id'], ['inventory_movements.id'], name=op.f('fk_inventory_count_revisions_movement_id_inventory_movements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_count_revisions')),
    sa.UniqueConstraint('count_id', 'revision', name=op.f('uq_inventory_count_revisions_count_id')),
    sa.UniqueConstraint('movement_id', name=op.f('uq_inventory_count_revisions_movement_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('operational_tasks',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('owner_role', sa.String(length=24), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('policy_version_id', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_operational_tasks_completed_by_users')),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], name=op.f('fk_operational_tasks_policy_version_id_policy_versions')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_operational_tasks_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_tasks')),
    sa.UniqueConstraint('store_id', 'source_type', 'source_id', 'task_type', name=op.f('uq_operational_tasks_store_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('operational_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operational_tasks_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_tasks_store_id'), ['store_id'], unique=False)

    op.create_table('replenishment_runs',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('store_version', sa.Integer(), nullable=False),
    sa.Column('baseline_at', sa.DateTime(), nullable=False),
    sa.Column('actual_generated_at', sa.DateTime(), nullable=False),
    sa.Column('data_through_at', sa.DateTime(), nullable=False),
    sa.Column('risk_evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('warning_version', sa.String(length=16), nullable=False),
    sa.Column('calculation_mode', sa.String(length=32), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_replenishment_runs_actor_id_users')),
    sa.ForeignKeyConstraint(['cycle_id'], ['delivery_cycles.id'], name=op.f('fk_replenishment_runs_cycle_id_delivery_cycles')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_replenishment_runs_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replenishment_runs'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('replenishment_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replenishment_runs_store_id'), ['store_id'], unique=False)

    op.create_table('sales_daily',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('interval_start', sa.DateTime(), nullable=False),
    sa.Column('interval_end', sa.DateTime(), nullable=False),
    sa.Column('sold_qty', sa.Integer(), nullable=False),
    sa.Column('was_stockout', sa.Boolean(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('import_mode', sa.String(length=24), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('event_note', sa.String(length=500), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('sold_qty >= 0', name=op.f('ck_sales_daily_sold_qty')),
    sa.ForeignKeyConstraint(['batch_id'], ['sales_import_batches.id'], name=op.f('fk_sales_daily_batch_id_sales_import_batches')),
    sa.ForeignKeyConstraint(['movement_id'], ['inventory_movements.id'], name=op.f('fk_sales_daily_movement_id_inventory_movements')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_daily_product_id_products')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_sales_daily_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_daily')),
    sa.UniqueConstraint('movement_id', name=op.f('uq_sales_daily_movement_id')),
    sa.UniqueConstraint('store_id', 'product_id', 'business_date', name=op.f('uq_sales_daily_store_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('sales_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_daily_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_daily_store_id'), ['store_id'], unique=False)

    op.create_table('count_submission_keys',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['inventory_count_revisions.id'], name=op.f('fk_count_submission_keys_revision_id_inventory_count_revisions')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_count_submission_keys_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_count_submission_keys_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_count_submission_keys')),
    sa.UniqueConstraint('store_id', 'user_id', 'request_key', name=op.f('uq_count_submission_keys_store_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('order_drafts',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('parent_order_id', sa.Integer(), nullable=True),
    sa.Column('additional_order_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['delivery_cycles.id'], name=op.f('fk_order_drafts_cycle_id_delivery_cycles')),
    sa.ForeignKeyConstraint(['run_id'], ['replenishment_runs.id'], name=op.f('fk_order_drafts_run_id_replenishment_runs')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_order_drafts_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_order_drafts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_drafts'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('order_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_drafts_store_id'), ['store_id'], unique=False)

    op.create_table('run_items',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('mu', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('target_stock', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('raw_qty', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('suggested_qty', sa.Integer(), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('output_snapshot', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('suggested_qty IS NULL OR (suggested_qty >= 0 AND suggested_qty <= 1000000)', name=op.f('ck_run_items_suggested_qty')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_run_items_product_id_products')),
    sa.ForeignKeyConstraint(['run_id'], ['replenishment_runs.id'], name=op.f('fk_run_items_run_id_replenishment_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_items')),
    sa.UniqueConstraint('run_id', 'product_id', name=op.f('uq_run_items_run_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('draft_items',
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('run_item_id', sa.Integer(), nullable=False),
    sa.Column('final_qty', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('special_need', sa.JSON(), nullable=True),
    sa.Column('manual_forecast_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('final_qty >= 0 AND final_qty <= 1000000', name=op.f('ck_draft_items_final_qty')),
    sa.ForeignKeyConstraint(['draft_id'], ['order_drafts.id'], name=op.f('fk_draft_items_draft_id_order_drafts')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_draft_items_product_id_products')),
    sa.ForeignKeyConstraint(['run_item_id'], ['run_items.id'], name=op.f('fk_draft_items_run_item_id_run_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_items')),
    sa.UniqueConstraint('draft_id', 'product_id', name=op.f('uq_draft_items_draft_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('orders',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('fixture_only', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['delivery_cycles.id'], name=op.f('fk_orders_cycle_id_delivery_cycles')),
    sa.ForeignKeyConstraint(['draft_id'], ['order_drafts.id'], name=op.f('fk_orders_draft_id_order_drafts')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_orders_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('draft_id', name=op.f('uq_orders_draft_id')),
    sa.UniqueConstraint('number', name=op.f('uq_orders_number'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_store_id'), ['store_id'], unique=False)

    op.create_table('order_confirmations',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('draft_version', sa.Integer(), nullable=False),
    sa.Column('store_version', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('text_version', sa.String(length=32), nullable=False),
    sa.Column('warning_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('risk_evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('order_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('exception_acknowledgements', sa.JSON(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['order_drafts.id'], name=op.f('fk_order_confirmations_draft_id_order_drafts')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_confirmations_order_id_orders')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_order_confirmations_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_order_confirmations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_confirmations')),
    sa.UniqueConstraint('order_id', name=op.f('uq_order_confirmations_order_id')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_order_confirmations_token_hash'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('order_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_confirmations_draft_id'), ['draft_id'], unique=False)

    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('original_qty', sa.Integer(), nullable=False),
    sa.Column('product_snapshot', sa.JSON(), nullable=False),
    sa.Column('committed_qty', sa.Integer(), nullable=False),
    sa.Column('cancelled_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('deduction_expires_at', sa.DateTime(), nullable=False),
    sa.Column('commitment_disputed', sa.Boolean(), nullable=False),
    sa.Column('disputed_qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('committed_qty >= 0 AND cancelled_qty >= 0 AND disputed_qty >= 0', name=op.f('ck_order_items_fulfillment_qty')),
    sa.CheckConstraint('original_qty > 0 AND original_qty <= 1000000', name=op.f('ck_order_items_original_qty')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    sa.UniqueConstraint('order_id', 'product_id', name=op.f('uq_order_items_order_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('shipments',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_shipments_actor_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_shipments_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipments')),
    sa.UniqueConstraint('order_id', 'request_key', name=op.f('uq_shipments_order_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('submission_keys',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_submission_keys_order_id_orders')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_submission_keys_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_submission_keys_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_keys')),
    sa.UniqueConstraint('user_id', 'store_id', 'key', name=op.f('uq_submission_keys_user_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('fulfillment_events',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_fulfillment_events_actor_id_users')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_fulfillment_events_order_item_id_order_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fulfillment_events')),
    sa.UniqueConstraint('source_key', name=op.f('uq_fulfillment_events_source_key'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('fulfillment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fulfillment_events_order_item_id'), ['order_item_id'], unique=False)

    op.create_table('receipts',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_receipts_shipment_id_shipments')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_receipts_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_receipts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts')),
    sa.UniqueConstraint('store_id', 'user_id', 'shipment_id', 'request_key', name=op.f('uq_receipts_store_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('shipment_items',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('authorization_id', sa.Integer(), nullable=True),
    sa.Column('shipped_qty', sa.Integer(), nullable=False),
    sa.Column('checked_qty', sa.Integer(), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=False),
    sa.Column('eta_disputed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("(kind = 'original' AND authorization_id IS NULL) OR (kind = 'replacement' AND authorization_id IS NOT NULL)", name=op.f('ck_shipment_items_kind_authorization')),
    sa.CheckConstraint('shipped_qty > 0 AND checked_qty >= 0 AND checked_qty <= shipped_qty', name=op.f('ck_shipment_items_quantities')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_shipment_items_order_item_id_order_items')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_shipment_items_shipment_id_shipments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_items')),
    sa.UniqueConstraint('shipment_id', 'order_item_id', 'kind', name=op.f('uq_shipment_items_shipment_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('supply_change_requests',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('old_conditions', sa.JSON(), nullable=False),
    sa.Column('new_conditions', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('response_due_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('responded_by', sa.Integer(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_supply_change_requests_created_by_users')),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_supply_change_requests_order_item_id_order_items')),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], name=op.f('fk_supply_change_requests_responded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supply_change_requests'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    with op.batch_alter_table('supply_change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_change_requests_order_item_id'), ['order_item_id'], unique=False)

    op.create_table('receipt_items',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('shipment_item_id', sa.Integer(), nullable=False),
    sa.Column('checked_qty', sa.Integer(), nullable=False),
    sa.Column('sellable_qty', sa.Integer(), nullable=False),
    sa.Column('damaged_qty', sa.Integer(), nullable=False),
    sa.Column('short_qty', sa.Integer(), nullable=False),
    sa.Column('inventory_source_id', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('checked_qty > 0 AND sellable_qty >= 0 AND damaged_qty >= 0 AND short_qty >= 0 AND checked_qty = sellable_qty + damaged_qty + short_qty', name=op.f('ck_receipt_items_quantities')),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name=op.f('fk_receipt_items_receipt_id_receipts')),
    sa.ForeignKeyConstraint(['shipment_item_id'], ['shipment_items.id'], name=op.f('fk_receipt_items_shipment_item_id_shipment_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt_items')),
    sa.UniqueConstraint('inventory_source_id', name=op.f('uq_receipt_items_inventory_source_id')),
    sa.UniqueConstraint('receipt_id', 'shipment_item_id', name=op.f('uq_receipt_items_receipt_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('receipt_variances',
    sa.Column('receipt_item_id', sa.Integer(), nullable=False),
    sa.Column('parent_variance_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('closed_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0 AND closed_qty >= 0 AND closed_qty <= quantity', name=op.f('ck_receipt_variances_quantities')),
    sa.ForeignKeyConstraint(['parent_variance_id'], ['receipt_variances.id'], name=op.f('fk_receipt_variances_parent_variance_id_receipt_variances')),
    sa.ForeignKeyConstraint(['receipt_item_id'], ['receipt_items.id'], name=op.f('fk_receipt_variances_receipt_item_id_receipt_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt_variances')),
    sa.UniqueConstraint('receipt_item_id', 'kind', name=op.f('uq_receipt_variances_receipt_item_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    op.create_table('replacement_authorizations',
    sa.Column('variance_id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('authorized_qty', sa.Integer(), nullable=False),
    sa.Column('used_qty', sa.Integer(), nullable=False),
    sa.Column('closed_qty', sa.Integer(), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('authorized_qty > 0 AND used_qty >= 0 AND closed_qty >= 0 AND used_qty + closed_qty <= authorized_qty', name=op.f('ck_replacement_authorizations_quantities')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_replacement_authorizations_actor_id_users')),
    sa.ForeignKeyConstraint(['variance_id'], ['receipt_variances.id'], name=op.f('fk_replacement_authorizations_variance_id_receipt_variances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replacement_authorizations')),
    sa.UniqueConstraint('variance_id', 'request_key', name=op.f('uq_replacement_authorizations_variance_id'))
    ,mysql_engine='InnoDB', mysql_charset='utf8mb4'
    )
    # ### end Alembic commands ###

    op.create_foreign_key('fk_draft_parent_order', 'order_drafts', 'orders', ['parent_order_id'], ['id'])
    op.create_foreign_key('fk_shipment_authorization', 'shipment_items', 'replacement_authorizations', ['authorization_id'], ['id'])


def downgrade():
    op.drop_constraint('fk_shipment_authorization', 'shipment_items', type_='foreignkey')
    op.drop_constraint('fk_draft_parent_order', 'order_drafts', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replacement_authorizations')
    op.drop_table('receipt_variances')
    op.drop_table('receipt_items')
    with op.batch_alter_table('supply_change_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_change_requests_order_item_id'))

    op.drop_table('supply_change_requests')
    op.drop_table('shipment_items')
    op.drop_table('receipts')
    with op.batch_alter_table('fulfillment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fulfillment_events_order_item_id'))

    op.drop_table('fulfillment_events')
    op.drop_table('submission_keys')
    op.drop_table('shipments')
    op.drop_table('order_items')
    with op.batch_alter_table('order_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_confirmations_draft_id'))

    op.drop_table('order_confirmations')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_store_id'))

    op.drop_table('orders')
    op.drop_table('draft_items')
    op.drop_table('run_items')
    with op.batch_alter_table('order_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_drafts_store_id'))

    op.drop_table('order_drafts')
    op.drop_table('count_submission_keys')
    with op.batch_alter_table('sales_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_daily_store_id'))
        batch_op.drop_index(batch_op.f('ix_sales_daily_product_id'))

    op.drop_table('sales_daily')
    with op.batch_alter_table('replenishment_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replenishment_runs_store_id'))

    op.drop_table('replenishment_runs')
    with op.batch_alter_table('operational_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_tasks_store_id'))
        batch_op.drop_index(batch_op.f('ix_operational_tasks_due_at'))

    op.drop_table('operational_tasks')
    op.drop_table('inventory_count_revisions')
    op.drop_table('sales_import_batches')
    with op.batch_alter_table('manual_forecast_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_forecast_overrides_store_id'))
        batch_op.drop_index(batch_op.f('ix_manual_forecast_overrides_product_id'))

    op.drop_table('manual_forecast_overrides')
    with op.batch_alter_table('inventory_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_reconciliations_store_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_reconciliations_product_id'))

    op.drop_table('inventory_reconciliations')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_store_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_product_id'))

    op.drop_table('inventory_movements')
    with op.batch_alter_table('inventory_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_counts_store_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_counts_product_id'))

    op.drop_table('inventory_counts')
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventories_store_id'))
        batch_op.drop_index(batch_op.f('ix_inventories_product_id'))

    op.drop_table('inventories')
    # ### end Alembic commands ###
